<script setup lang="ts">
import { useI18n } from "vue-i18n";
const { t } = useI18n();
import { ref, onMounted } from "vue";
import { useRouter } from "vue-router";
import { useForm } from "vee-validate";
import { toTypedSchema } from "@vee-validate/zod";
import * as z from "zod";
import { Button } from "@/components/ui/button";

import {
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";

import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";

import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardFooter,
} from "@/components/ui/card";
import { ChevronLeft, Loader2 } from "lucide-vue-next";
import { BrandService } from "@/services/brand/brand.service";
import ImageUpload from "@/components/upload/ImageUpload.vue";
import type { Brand } from "@/types/brand";
import { toast } from "vue-sonner";


const router = useRouter();
const brandService = new BrandService();

const parentBrands = ref<Brand[]>([]);
const loading = ref(false);
const submitting = ref(false);

const formSchema = toTypedSchema(
  z.object({
    name: z.string().min(2, "Name must be at least 2 characters").max(60),
    parentId: z.string().optional(),
    description: z.string().optional(),
    imageUrl: z.string().optional(),
    status: z.boolean().default(true),
  }),
);

const form = useForm({
  validationSchema: formSchema,
  initialValues: {
    name: "",
    description: "",
    imageUrl: "",
    status: true,
  },
});

async function fetchParentBrands() {
  loading.value = true;
  try {
    const response = await brandService.getAll();
    if (response.success && response.data) {
      parentBrands.value = response.data;
    }
  } catch (error) {
    console.error("Failed to fetch brands", error);
  } finally {
    loading.value = false;
  }
}

const onSubmit = form.handleSubmit(async (values) => {
  submitting.value = true;
  try {
    const payload = {
      ...values,
      parentId:
        values.parentId && values.parentId !== "0"
          ? Number(values.parentId)
          : undefined,
    };
    const response = await brandService.create(payload);
    if (response.success) {
      toast.success(t('crud.successCreate', { module: t('modules.brand') }));
      router.push("/admin/brands");
    } else {
      toast.error(response.message || t('crud.errorCreate', { module: t('modules.brand') }));
    }
  } catch (error) {
    toast.error(t('crud.errorGeneral'));
  } finally {
    submitting.value = false;
  }
});

// Code and slug are auto-generated by the backend

onMounted(() => {
  fetchParentBrands();
});
</script>

<template>
  <div class="space-y-4">
    <div class="flex items-center gap-4">
      <Button variant="outline" size="icon" @click="router.back()">
        <ChevronLeft class="h-4 w-4" />
      </Button>
      <h2 class="text-3xl font-bold tracking-tight">{{ $t('crud.create', { module: $t('modules.brand') }) }}</h2>
    </div>

    <Card>
      <CardHeader>
        <CardTitle>{{ $t('crud.info', { module: $t('modules.brand') }) }}</CardTitle>
      </CardHeader>
      <CardContent>
        <form @submit="onSubmit" id="brandForm" class="space-y-6">
          <div class="flex flex-col lg:flex-row gap-8">
            <!-- Left Side: Image Upload -->
            <div class="flex flex-col items-center gap-4 shrink-0">
              <FormField v-slot="{ value, handleChange }" name="imageUrl">
                <FormItem>
                  <FormLabel
                    class="text-sm font-bold uppercase tracking-wider text-muted-foreground/80"
                    >{{ $t('modules.brand') }} {{ $t('crud.image') }}</FormLabel
                  >
                  <FormControl>
                    <ImageUpload
                      :image-url="value"
                      @update:image-url="handleChange"
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              </FormField>
            </div>

            <!-- Right Side: Form Fields -->
            <div class="flex-1 space-y-6">
              <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                <FormField v-slot="{ componentField }" name="name">
                  <FormItem>
                    <FormLabel>{{ $t('fields.name') }}</FormLabel>
                    <FormControl>
                      <Input
                        placeholder="Brand Name"
                        v-bind="componentField"
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                </FormField>

                <FormField v-slot="{ field }" name="parentId">
                  <FormItem>
                    <FormLabel>{{ $t('fields.parentOf', { module: $t('modules.brand') }) }}</FormLabel>
                    <Select v-bind="field">
                      <FormControl>
                        <SelectTrigger>
                          <SelectValue placeholder="Select a parent brand" />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        <SelectItem value="0">{{ $t('crud.none') }}</SelectItem>
                        <SelectItem
                          v-for="brand in parentBrands"
                          :key="brand.id"
                          :value="String(brand.id)"
                        >
                          {{ brand.name }}
                        </SelectItem>
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                </FormField>

                <div class="md:col-span-2">
                  <FormField v-slot="{ componentField }" name="description">
                    <FormItem>
                      <FormLabel>{{ $t('fields.description') }}</FormLabel>
                      <FormControl>
                        <Input
                          placeholder="Enter brand description"
                          v-bind="componentField"
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  </FormField>
                </div>

                <div class="md:col-span-2">
                  <FormField name="status">
                    <FormItem
                      class="flex flex-row items-center justify-between rounded-lg border p-4"
                    >
                      <div class="space-y-0.5">
                        <FormLabel class="text-base font-semibold"
                          >{{ $t('fields.activeStatus') }}</FormLabel
                        >
                        <FormDescription>
                          {{ $t('fields.statusDescription', { module: $t('modules.brand') }) }}
                        </FormDescription>
                      </div>
                      <FormControl>
                        <Switch v-model="form.values.status" />
                      </FormControl>
                    </FormItem>
                  </FormField>
                </div>
              </div>
            </div>
          </div>
        </form>
      </CardContent>
      <CardFooter class="flex justify-end gap-2 border-t px-6 py-4">
        <Button variant="outline" @click="router.back()" :disabled="submitting">{{ $t('crud.cancel') }}</Button>
        <Button type="submit" form="brandForm" :disabled="submitting">
          <Loader2 v-if="submitting" class="mr-2 h-4 w-4 animate-spin" />{{ $t('crud.create', { module: $t('modules.brand') }) }}</Button>
      </CardFooter>
    </Card>
  </div>
</template>
