<script setup lang="ts">
import { ref, onMounted } from "vue";
import { useRouter } from "vue-router";
import { useForm } from "vee-validate";
import { toTypedSchema } from "@vee-validate/zod";
import * as z from "zod";
import { Button } from "@/components/ui/button";
import {
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardFooter,
} from "@/components/ui/card";
import { ChevronLeft, Loader2 } from "lucide-vue-next";
import { CategoryService } from "@/services/category/category.service";
import ImageUpload from "@/components/upload/ImageUpload.vue";
import type { Category } from "@/types/category";
import { toast } from "vue-sonner";

const router = useRouter();
const categoryService = new CategoryService();

const parentCategories = ref<Category[]>([]);
const loading = ref(false);
const submitting = ref(false);

const formSchema = toTypedSchema(
  z.object({
    name: z.string().min(2, "Name must be at least 2 characters").max(60),
    parentId: z.string().optional(),
    description: z.string().optional(),
    imageUrl: z.string().optional(),
    status: z.boolean().default(true),
  }),
);

const form = useForm({
  validationSchema: formSchema,
  initialValues: {
    name: "",
    description: "",
    imageUrl: "",
    status: true,
  },
});

async function fetchParentCategories() {
  loading.value = true;
  try {
    const response = await categoryService.getAll();
    if (response.success && response.data) {
      parentCategories.value = response.data;
    }
  } catch (error) {
    console.error("Failed to fetch categories", error);
  } finally {
    loading.value = false;
  }
}

const onSubmit = form.handleSubmit(async (values) => {
  submitting.value = true;
  try {
    const payload = {
      ...values,
      parentId:
        values.parentId && values.parentId !== "0"
          ? Number(values.parentId)
          : undefined,
    };
    const response = await categoryService.create(payload);
    if (response.success) {
      toast.success("Category created successfully");
      router.push("/admin/categories");
    } else {
      toast.error(response.message || "Failed to create category");
    }
  } catch (error) {
    toast.error("An error occurred while creating the category");
  } finally {
    submitting.value = false;
  }
});

// Code and slug are auto-generated by the backend

onMounted(() => {
  fetchParentCategories();
});
</script>

<template>
  <div class="space-y-4">
    <div class="flex items-center gap-4">
      <Button variant="outline" size="icon" @click="router.back()">
        <ChevronLeft class="h-4 w-4" />
      </Button>
      <h2 class="text-3xl font-bold tracking-tight">Create Category</h2>
    </div>

    <Card>
      <CardHeader>
        <CardTitle>Category Information</CardTitle>
      </CardHeader>
      <CardContent>
        <form @submit="onSubmit" id="categoryForm" class="space-y-6">
          <div class="flex flex-col lg:flex-row gap-8">
            <!-- Left Side: Image Upload -->
            <div class="flex flex-col items-center gap-4 shrink-0">
              <FormField v-slot="{ value, handleChange }" name="imageUrl">
                <FormItem>
                  <FormLabel
                    class="text-sm font-bold uppercase tracking-wider text-muted-foreground/80"
                    >Category Image</FormLabel
                  >
                  <FormControl>
                    <ImageUpload
                      :image-url="value"
                      @update:image-url="handleChange"
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              </FormField>
            </div>

            <!-- Right Side: Form Fields -->
            <div class="flex-1 space-y-6">
              <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                <FormField v-slot="{ componentField }" name="name">
                  <FormItem>
                    <FormLabel>Name</FormLabel>
                    <FormControl>
                      <Input
                        placeholder="Category Name"
                        v-bind="componentField"
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                </FormField>

                <FormField v-slot="{ field }" name="parentId">
                  <FormItem>
                    <FormLabel>Parent Category</FormLabel>
                    <Select v-bind="field">
                      <FormControl>
                        <SelectTrigger>
                          <SelectValue placeholder="Select a parent category" />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        <SelectItem value="0">None</SelectItem>
                        <SelectItem
                          v-for="cat in parentCategories"
                          :key="cat.id"
                          :value="String(cat.id)"
                        >
                          {{ cat.name }}
                        </SelectItem>
                      </SelectContent>
                    </Select>
                    <FormMessage />
                  </FormItem>
                </FormField>

                <div class="md:col-span-2">
                  <FormField v-slot="{ componentField }" name="description">
                    <FormItem>
                      <FormLabel>Description</FormLabel>
                      <FormControl>
                        <Input
                          placeholder="Enter category description"
                          v-bind="componentField"
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  </FormField>
                </div>

                <div class="md:col-span-2">
                  <FormField name="status">
                    <FormItem
                      class="flex flex-row items-center justify-between rounded-lg border p-4"
                    >
                      <div class="space-y-0.5">
                        <FormLabel class="text-base font-semibold"
                          >Active Status</FormLabel
                        >
                        <FormDescription>
                          Enable or disable this category.
                        </FormDescription>
                      </div>
                      <FormControl>
                        <Switch v-model="form.values.status" />
                      </FormControl>
                    </FormItem>
                  </FormField>
                </div>
              </div>
            </div>
          </div>
        </form>
      </CardContent>
      <CardFooter class="flex justify-end gap-2 border-t px-6 py-4">
        <Button variant="outline" @click="router.back()" :disabled="submitting">
          Cancel
        </Button>
        <Button type="submit" form="categoryForm" :disabled="submitting">
          <Loader2 v-if="submitting" class="mr-2 h-4 w-4 animate-spin" />
          Create Category
        </Button>
      </CardFooter>
    </Card>
  </div>
</template>
